apiVersion: velero.io/v1
kind: BackupStorageLocation
metadata:
  name: default
  namespace: velero
spec:
  provider: aws
  objectStorage:
    bucket: velero
    prefix: velero
  config:
    region: minio
    s3ForcePathStyle: "true"
    s3Url: http://minio.minio-system.svc.cluster.local:9000
