apiVersion: v1
kind: Namespace
metadata:
  name: bots
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: telegram-bot-sa
  namespace: bots
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: telegram-bot-role
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "nodes"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: telegram-bot-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: telegram-bot-role
subjects:
  - kind: ServiceAccount
    name: telegram-bot-sa
    namespace: bots
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegram-k8s-bot
  namespace: bots
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telegram-k8s-bot
  template:
    metadata:
      labels:
        app: telegram-k8s-bot
    spec:
      serviceAccountName: telegram-bot-sa
      containers:
        - name: bot
          image: sharpwoden/telegram-k8s-bot:0.1
          env:
            - name: TELEGRAM_BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: telegram-bot-secret
                  key: TELEGRAM_BOT_TOKEN