# docker-compose.yml
version: '3.8'

services:
  db:
    image: postgres:16
    container_name: invest-db
    environment:
      POSTGRES_DB: invest
      POSTGRES_USER: invest_user
      POSTGRES_PASSWORD: secure_password_123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U invest_user -d invest"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata: